# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: UTB
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'esneider23/app-deploy'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Provision
  displayName: 'Creating terraform on Azure'
  jobs:
    - job: provision
      displayName: 'Provision instance'
      pool:
        name: UTB
      variables: 
      - group: var
      steps:
        - script: |
            set -e 

            terraform init -input=false
            terraform apply -input=false -auto-approve
          name: 'RunTerraform'
          displayName: 'Run Terraform'
          env: 
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            TF_VAR_imagebuild: $(tag)

